Add styling to documentation pages
symphonyoss/ContainerJS pull request #181
Opened 2017-06-07 13:02 UTC by BenLambertNcl

Add new styling to documentation pages. Sample:
![image](https://user-images.githubusercontent.com/9324259/26879646-d47714c8-4b89-11e7-8fbf-640ee808a680.png)

![image](https://user-images.githubusercontent.com/9324259/26879634-c8f73862-4b89-11e7-98c3-a383530a4d2d.png)

2017-06-07 13:58 UTC, ColinEberhardt requested changes
Looks really good to me - the one part I'm unsure of is the need for the extra 'navigation' file. Typically navigation structures are constructed from the page meta-data, via the `pages` Jekyll variable.

2017-06-07 13:58 UTC, ColinEberhardt commented on packages/api-specification/transform-type-info.js
> +            p(`${d.match.results.browser.passed}/${d.match.results.browser.total}`, {class: 'test-result ' + testResultPercentage(d.match.results.browser.passed, d.match.results.browser.total)})
A few very minor points ...

- I don't think `p` tags make much sense here, how about `h5` for the container name, and a `span` for the results
- There's a bit of duplication on the 3 lines that output the results, might be worth moving into a separate function.

2017-06-07 14:14 UTC, BenLambertNcl commented
The navigation page is needed because the docs is now outputted as 1 file, so we need a way of being able to generate the menu. We could do this with JavaScript if you think that's a better option?

2017-06-07 14:29 UTC, ColinEberhardt commented
> The navigation page is needed because the docs is now outputted as 1 file, so we need a way of being able to generate the menu. We could do this with JavaScript if you think that's a better option?

Good point, and I agree, using JavaScript would be better. I'd avoid making the Jekyll template and configuration any more complicated than it needs to be,

2017-06-07 15:43 UTC, BenLambertNcl commented
Updated :-)

2017-06-08 07:50 UTC, ColinEberhardt commented on packages/api-specification/transform-type-info.js
> +            ...testResults('Electron', d.match.results.electron),
nice use of spread 👍

2017-06-08 07:51 UTC, ColinEberhardt approved these changes
thanks for the updates -looks really good.

2017-06-08 10:09 UTC, merged