Change window methods to be promise based
symphonyoss/ContainerJS pull request #54
Opened 2017-04-06 12:47 UTC by BenLambertNcl

Change methods in the window API to return promises. This normalizes the APIs to all be asynchronous.

2017-04-06 13:17 UTC, ColinEberhardt requested changes

2017-04-06 13:17 UTC, ColinEberhardt commented on packages/api-browser/src/window.js
> +    return new Promise((resolve, reject) => {
How about refactoring to remove some of the repetition? For example:

```
const withInnerWindow(fn) =>
  new Promise((resolve, reject) => {
      if (this.innerWindow) {
        fn(this.innerWindow);
        resolve();
      } else {
        reject(windowClosedError);
      }
    });
```

Then `close` becomes the following:

```
  close() {
    return withInnerWindow(innerWindow => innerWindow.close());
  }
```

2017-04-06 13:17 UTC, ColinEberhardt commented on packages/api-electron/index.js
> +  getWindowFromId(id, (win) => {
You've got a similarly repeated pattern here that could be factored out.

2017-04-06 13:17 UTC, ColinEberhardt commented on packages/api-specification/src/window/window-api.md
> +* `blur()` - Remove focus from the window. Returns a promise
You should probably mention what the promise resolves to? Even if it resolves to nothing!

2017-04-07 07:58 UTC, BenLambertNcl commented
Ready for re-review. I have added a small change to the OpenFin API to run the reject function when the window has been closed, keeping it in line with the Electron API.

2017-04-07 08:13 UTC, ColinEberhardt approved these changes

2017-04-07 08:27 UTC, merged